

export const GET_FLIGHT_OPTION_REQUEST = "GET_FLIGHT_OPTION_REQUEST";
export const GET_FLIGHT_OPTION_SUCCESS = "GET_FLIGHT_OPTION_SUCCESS";
export const GET_FLIGHT_OPTION_FAILURE = "GET_FLIGHT_OPTION_FAILURE";
